name: flutter_arch_starter # <-- TODO rename after using the template
description: Starter with app/shared/features + custom layer lint + neutral l10n
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: 10.2.0
  cupertino_icons: 1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: 9.1.1
  freezed_annotation: 3.1.0
  get_it: 8.2.0
  injectable: 2.5.2
  intl: 0.20.2

dev_dependencies:
  auto_route_generator: 10.2.5
  bloc_test: 10.0.0
  build_runner: 2.10.1
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  freezed: 3.2.3
  injectable_generator: 2.9.0
  mocktail: 1.0.4

dependency_overrides:
  # Fix for bloc_text conflict with test_api: https://github.com/felangel/bloc/issues/4662
  test_api: ^0.7.6

flutter:
  uses-material-design: true
  generate: true
